#!/usr/bin/env python3
# Author: pidpawel <pidpawel.eu>
# URL: https://pidpawel.eu/zoo/
# License: CC-BY-SA http://creativecommons.org/licenses/by-sa/3.0/pl/
import zoolib
import argparse
import time

parser = argparse.ArgumentParser(description='Execute command on zoo hosts')
parser.add_argument('-n', '--nodes', dest='nodes', action='store_true', help='Execute on nodes.')
parser.add_argument('-s', '--special', dest='special', action='store_true', help='Execute on special cluster hosts.')
parser.add_argument('-a', '--avahi', dest='avahi', action='store_true', help='Execute on all avahi declared ssh hosts.')
parser.set_defaults(nodes=False)
parser.set_defaults(special=False)
parser.set_defaults(avahi=False)

parser.add_argument('-r', '--random', dest='random', action='store_true', help='Execute on random host instead of all hosts.')
parser.set_defaults(random=False)

parser.add_argument('-d', '--delay', type=float, default=0, help='Delay between executing commands on succesive hosts.')

parser.add_argument('command', nargs='+', help='Command to execute')

args = parser.parse_args()

targets = []
if args.avahi:
	targets.append('avahi')
if args.nodes:
	targets.append('nodes')
if args.special:
	targets.append('special')

hosts = zoolib.discovery(targets=targets)
cmd = ' '.join(args.command)

if args.random:
	import random
	hosts = [ hosts[random.randint(0, len(hosts)-1)] ]

if args.delay == 0 and len(hosts) > 1:
	results = zoolib.cluster_exec(hosts, cmd)
	for host, r in results.items():
		print(host + ': ' + r.rstrip('\n'))
else:
	if len(hosts) > 1:
		print("Found {} hosts, will take about {} seconds to execute.".format(
					len(hosts),
					int(len(hosts)*args.delay)))

	for host in hosts:
		print("Executing on {}".format( host ))
		print(zoolib.host_exec(host, cmd))
		time.sleep(args.delay)
